snd-soc-spacemit-objs := spacemit-snd-pcm.o  spacemit-snd-sspa.o \
			spacemit-snd-adsp.o spacemit-snd-ipc.o spacemit-snd-memory.o \
			spacemit-snd-soc.o spacemit-snd-card.o
obj-$(CONFIG_SND_SOC_SPACEMIT) += snd-soc-spacemit.o
