# SPDX-License-Identifier: GPL-2.0

spacemit-drm-y := 	spacemit_drm.o \
				spacemit_cmdlist.o \
				spacemit_dpu.o \
				spacemit_planes.o \
				spacemit_lib.o \
				spacemit_gem.o \
				spacemit_dmmu.o \
				dpu/dpu_debug.o \
				dpu/dpu_saturn.o \
				dpu/saturn_fbcmem.o \


obj-$(CONFIG_DRM_SPACEMIT) += spacemit-drm.o

obj-$(CONFIG_SPACEMIT_HDMI) += spacemit_hdmi.o